_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 03d801ee-f531-4faf-905f-5bf71bf2a228
name: nathdrupalbuildtools
mail: nathaniel.villanueva@getpantheon.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
